# 读取数据

In [2]:
import pandas as pd

# 方式1：CSV 和 notebook 在同一目录
df = pd.read_csv("../2020年裁判文书数据_马克数据网/2020年01月裁判文书数据.csv")

# 查看条数
print("筛选前条数：", len(df))

# 查看前5行
df.head()

筛选前条数： 923796

,原始链接,案号,案件名称,法院,所属地区,案件类型,案件类型编码,来源,审理程序,裁判日期,公开日期,当事人,案由,法律依据,全文
0,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）新42民辖终45号,江鹏程与新疆泰华房地产开发有限公司、于水勇借款合同纠纷管辖民事裁定书,新疆维吾尔自治区塔城地区中级人民法院,NaN,管辖案件,5,www.macrodatas.cn,民事管辖,2020-01-01,2020-01-05,江鹏程；新疆泰华房地产开发有限公司；于水勇,借款合同纠纷,《中华人民共和国民事诉讼法》:第一百七十条第一款第二项；《中华人民共和国民事诉讼法》:第一百...,新疆维吾尔自治区伊犁哈萨克自治州塔城地区中级人民法院 民 事 裁 定 书 （2019）新4...
1,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）鄂01财保490号,联储证券有限责任公司、北大方正集团有限公司其他民事裁定书,湖北省武汉市中级人民法院,湖北省武汉市,民事案件,1,www.macrodatas.cn,其他,2020-01-01,2020-01-03,联储证券有限责任公司；北大方正集团有限公司,申请保全案件,《中华人民共和国民事诉讼法》:第一百五十四条第一款第十一项,湖北省武汉市中级人民法院民 事 裁 定 书（2019）鄂01财保490号申请人：联储证券有限...
2,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）皖1323民初3437号,曹雪与李奎民间借贷纠纷,灵璧县人民法院,灵璧县,民事案件,1,www.macrodatas.cn,民事一审,2020-01-01,2020-01-02,李奎；曹雪,民间借贷纠纷,NaN,NaN
3,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）新42民辖终51号,袁玲伟、史秋英等与平安养老保险股份有限公司新疆分公司人身保险合同纠纷管辖民事裁定书,新疆维吾尔自治区塔城地区中级人民法院,NaN,管辖案件,5,www.macrodatas.cn,民事管辖,2020-01-01,2020-01-05,袁玲伟；史秋英；吴某；平安养老保险股份有限公司新疆分公司,人身保险合同纠纷,《中华人民共和国民事诉讼法》:第一百七十条第一款第二项；《中华人民共和国民事诉讼法》:第一百...,新疆维吾尔自治区伊犁哈萨克自治州塔城地区中级人民法院 民 事 裁 定 书 （2019）新4...
4,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）云0326执1104号,王朝磊、王明昌、刘兰兰与中国平安财产保险股份有限公司建水支公司机动车交通事故责任纠纷,会泽县人民法院,会泽县,执行案件,2,www.macrodatas.cn,执行实施,2020-01-01,2020-01-03,王朝磊；王明昌；刘兰兰；中国平安财产保险股份有限公司建水支公司,机动车交通事故责任纠纷,NaN,NaN

# 查看“案件类型”有多少种，非别是什么

In [30]:
df["案由"].unique()

array(['借款合同纠纷', '申请保全案件', '民间借贷纠纷', ..., '协助香港特别行政区送达司法文书',
       '公路货物运输合同纠纷；运输合同纠纷', '逃汇'], dtype=object)

In [32]:
df["案由"].nunique(dropna=False)

2444

In [34]:
# 打印查看

vals = pd.unique(df["案由"])   # 包含 NaN（如果有）
for v in vals:
    print(v)

借款合同纠纷
申请保全案件
民间借贷纠纷
人身保险合同纠纷
机动车交通事故责任纠纷
离婚纠纷
强奸
财产保险合同纠纷
追偿权纠纷
债权人代位权纠纷
生命权、健康权、身体权纠纷
金融借款合同纠纷
侵权责任纠纷
合伙协议纠纷
房屋租赁合同纠纷
其他案由
物业服务合同纠纷
所有权纠纷
合同纠纷
小额借款合同纠纷
买卖合同纠纷
nan
装饰装修合同纠纷
婚姻家庭纠纷
变更抚养关系纠纷
罚金
运输合同纠纷
行政复议
租赁合同纠纷
劳动争议
分家析产纠纷
危险驾驶
共有纠纷
保险人代位求偿权纠纷
合同、无因管理、不当得利纠纷
侵害作品信息网络传播权纠纷
商品房预售合同纠纷
房屋买卖合同纠纷
请求确认人民调解协议效力
承揽合同纠纷
婚姻家庭、继承纠纷
继承纠纷
车辆租赁合同纠纷
著作权权属、侵权纠纷
劳务合同纠纷
申请确认人民调解协议效力
企业借贷纠纷
行政处罚
服务合同纠纷
定作合同纠纷
建设工程合同纠纷
种植、养殖回收合同纠纷
供用热力合同纠纷
银行卡纠纷
行政监督
健康权纠纷
商品房销售合同纠纷
法定继承纠纷
非国家工作人员受贿
劳务派遣合同纠纷
与公司、证券、保险、票据等有关的民事纠纷
走私、贩卖、运输、制造毒品
教育培训合同纠纷
挂靠经营合同纠纷
故意杀人
追索劳动报酬纠纷
技术服务合同纠纷
相邻关系纠纷
网络购物合同纠纷
建设工程施工合同纠纷
劳动争议、人事争议
物权纠纷
确认合同无效纠纷
非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物
排除妨害纠纷
不当得利纠纷
抚养费纠纷
担保物权纠纷
非法经营
信用卡纠纷
公路货物运输合同纠纷
案外人执行异议之诉
供用气合同纠纷
财产保全
刑事
申请撤销仲裁裁决
赡养纠纷
财产损害赔偿纠纷
非法拘禁
融资租赁合同纠纷
申请支付令
保证合同纠纷
申请诉前财产保全
物权保护纠纷
民事
同居关系析产纠纷
票据付款请求权纠纷
公证损害责任纠纷
追缴违法所得
故意伤害
行政
行政强制
因申请诉前财产保全损害责任纠纷
其他行政管理
责令退赔
保险纠纷
提供劳务者受害责任纠纷
联营合同纠纷
农村土地承包合同纠纷
无因管理纠纷
同居关系子女抚养纠纷
抚养纠纷
离婚后财产纠纷
其他行政行为
遗嘱继承纠纷
盗窃
占有排除妨害纠纷
商标权权属、侵权纠纷
公司盈余分配纠纷
商品房预约合同纠纷
委托合同纠纷
交通肇事
诈骗
电信服务合同纠纷
提供劳务者致害责任纠纷
建设工程设计合同纠纷
广告合同纠纷
出租汽车运输合同纠纷
典当纠纷
工伤保险待遇纠纷
侵害实用新型专利权纠纷
加工合同纠纷
船员劳务合同纠纷
合同、无因管理、不当得利
抢劫
婚约财产纠纷
敲诈勒索
股东出资纠纷
计算机软件开发合同纠纷
建设工程分包合同纠纷
申请宣告公民无民事行为能力
分期付款买卖合同纠纷
对外追收债权纠纷
财会服务合同纠纷
传播性病
申请承认与执行法院判决、仲裁裁决案件；组织、领导、参加黑社会性质组织；敲诈勒索；诈骗；寻衅滋事；非法拘禁；非法侵入住宅
拒不支付劳动报酬
商业贿赂不正当竞争纠纷
股权转让纠纷
业主撤销权纠纷
保证保险合同纠纷
物权确认纠纷
居间合同纠纷
民政行政管理（民政）
建筑设备租赁合同纠纷
认定公民无民事行为能力、限制民事行为能力案件
旅游合同纠纷
广播电视播放合同纠纷
确认合同有效纠纷
网络侵权责任纠纷
同居关系纠纷
商标权转让合同纠纷
经济补偿金纠纷
人格权纠纷
寻衅滋事
侵害作品放映权纠纷
引诱幼女卖淫
修理合同纠纷
农村建房施工合同纠纷
损害公司利益责任纠纷
猥亵儿童
房屋拆迁安置补偿合同纠纷
引诱、容留、介绍卖淫
申请破产清算
储蓄存款合同纠纷
乡政府
民间委托理财合同纠纷
城市规划管理（规划）
确认劳动关系纠纷
建设工程监理合同纠纷
侵权
申请宣告公民死亡
非法吸收公众存款
医疗损害责任纠纷
债权人撤销权纠纷
其他（资源）
返还原物纠纷
侵害商标权纠纷
申请执行人执行异议之诉
人身自由权纠纷
所有权确认纠纷
用益物权纠纷
变更扶养关系纠纷
农机作业服务合同纠纷
重婚
共有物分割纠纷
申请确定监护人
劳务（雇佣）合同纠纷
金融不良债权追偿纠纷
产品责任纠纷
股东资格确认纠纷
供用电合同纠纷
土地行政管理（土地）
组织、利用会道门、邪教组织、利用迷信破坏法律实施
农村房屋买卖合同纠纷
承包地征收补偿费用分配纠纷
申请宣告公民失踪
网络服务合同纠纷
职务侵占；挪用资金
行政非诉执行
知识产权权属、侵权纠纷
国内非涉外仲裁裁决
附带民事赔偿
贪污
供用水合同纠纷
赡养费纠纷
票据追索权纠纷
股东知情权纠纷
委托理财合同纠纷
容留他人吸毒
土地租赁合同纠纷
与公司有关的纠纷
土地承包经营权纠纷
名誉权纠纷
其他（公安）
房屋登记管理（房屋登记）
卫生行政管理（卫生）
玩忽职守
组织、领导传销活动
申请公示催告
网络域名权属、侵权纠纷
职务侵占
错误执行赔偿
娱乐服务合同纠纷
债权转让合同纠纷
缔约过失责任纠纷
诉讼、仲裁、人民调解代理合同纠纷
饲养动物损害责任纠纷
侵害集体经济组织成员权益纠纷
特许经营合同纠纷
赠与合同纠纷
执行分配方案异议之诉
人格权
占有物返还纠纷
故意杀人；故意伤害
请求变更公司登记纠纷
肖像权纠纷
劳动合同纠纷
劳动争议；保险纠纷；侵权责任纠纷
人事争议
义务帮工人受害责任纠纷
执行异议之诉
质押合同纠纷
仓储合同纠纷
行政征收
协助组织卖淫
抵押合同纠纷
占有物损害赔偿纠纷
渔业承包合同纠纷
植物新品种权权属纠纷
追收未缴出资纠纷
道路交通管理（道路）
相邻土地、建筑物利用关系纠纷
恢复原状纠纷
劳动和社会保障行政管理（劳动、社会保障）
著作权许可使用合同纠纷
伪造、变造、买卖国家机关公文、证件、印章；伪造公司、企业、事业单位、人民团体印章
拒不执行判决、裁定
环境污染责任纠纷
虚开增值税专用发票、用于骗取出口退税、抵扣税款发票
申请保全案件；特殊程序
房屋拆迁管理（拆迁）
行政给付
探望权纠纷
行政确认
公司证照返还纠纷
公证债权文书
聚众斗殴
制作、复制、出版、贩卖、传播淫秽物品牟利
伪造、变造、买卖国家机关公文、证件、印章
海上、通海水域货运代理合同纠纷
遗赠纠纷
定金合同纠纷
被继承人债务清偿纠纷
产品销售者责任纠纷
宅基地使用权纠纷
行政补偿
环境保护行政管理（环保）
法律服务合同纠纷
行政撤销
股东损害公司债权人利益责任纠纷
适用特殊程序案件案由
非法持有毒品
违反安全保障义务责任纠纷
竞业限制纠纷
解除收养关系纠纷
扶养费纠纷
滥伐林木
农业承包合同纠纷
强迫交易
串通投标
清算责任纠纷
盗伐林木
产品生产者责任纠纷
其他刑事犯
侵害外观设计专利权纠纷
寻衅滋事；非法拘禁
身体权纠纷
不正当竞争纠纷
建设用地使用权合同纠纷
信用卡诈骗；妨害信用卡管理；洗钱
确认合同效力纠纷
餐饮服务合同纠纷
窝藏、包庇
财产刑
意外伤害保险合同纠纷
强制猥亵、侮辱
妨害公务
职务侵占；挪用资金；寻衅滋事
触电人身损害责任纠纷
普通破产债权确认纠纷
家政服务合同纠纷
企业出售合同纠纷
申请宣告公民限制民事行为能力
故意毁坏财物
破产债权确认纠纷
网络域名权属纠纷
公司决议纠纷
医疗服务合同纠纷
生产、销售伪劣产品
侵占
侵害发明专利权纠纷
财产损失保险合同纠纷
建设用地使用权纠纷
委托创作合同纠纷
凭样品买卖合同纠纷
转继承纠纷
退伙纠纷
走私国家禁止进出口的货物、物品
公共场所管理人责任纠纷
企业承包经营合同纠纷
以危险方法危害公共安全
非法行医
扶养纠纷
治安管理（治安）
林业承包合同纠纷
行纪合同纠纷
相邻通行纠纷
申请承认与执行法院判决、仲裁裁决案件
税务行政管理（税务）
挪用资金
组织卖淫
非法持有、私藏枪支、弹药
民事；民间借贷纠纷
生产、销售不符合安全标准的食品
业主知情权纠纷
绑架
强制猥亵、侮辱妇女
债务转移合同纠纷
开设赌场
诈骗；盗窃
技术合同纠纷
虚假诉讼
技术委托开发合同纠纷
虚开发票
公共道路妨碍通行损害责任纠纷
土地承包经营权互换合同纠纷
违法刑事拘留赔偿
生命权纠纷
共有权确认纠纷
合资、合作开发房地产合同纠纷
婚姻无效纠纷
非法占用农用地
与破产有关的纠纷
质量监督行政管理（质量监督）
一般人格权纠纷
仲裁程序中的财产保全
诈骗；合同诈骗
建设用地使用权转让合同纠纷
夫妻财产约定纠纷
一般取回权纠纷
单位受贿
非法采矿
公司决议撤销纠纷
借记卡纠纷；金融借款合同纠纷
物权
货运代理合同纠纷
申请船舶优先权催告
社会保险纠纷
申请公司清算
掩饰、隐瞒犯罪所得、犯罪所得收益
非法捕捞水产品
强奸；故意伤害
婚姻家庭、继承
水利行政管理（水利）
徇私枉法
遗弃
土地承包经营权出租合同纠纷
船舶物料和备品供应合同纠纷
借用合同纠纷
进出口代理合同纠纷
申请确认仲裁协议效力
滥用职权；受贿
受贿；贪污；滥用职权
船舶共有纠纷
小额借款合同纠纷；诉讼、仲裁、人民调解代理合同纠纷
离婚后损害责任纠纷
殡葬服务合同纠纷
请求确认债务人行为无效纠纷
保管合同纠纷
其他（质量监督）
司法行政管理（司法行政）
公司增资纠纷
窃取、收买、非法提供信用卡信息
建设用地使用权出让合同纠纷
建筑物、构筑物倒塌损害责任纠纷
与企业有关的纠纷
保安服务合同纠纷
姓名权纠纷
发起人责任纠纷
教育机构责任纠纷
责任保险合同纠纷
遗赠扶养协议纠纷
信用卡诈骗
不动产登记纠纷
损害股东利益责任纠纷
诈骗；伪造公司、企业、事业单位、人民团体印章
抢劫；敲诈勒索
海上、通海水域货物运输合同纠纷
诽谤
民间借贷纠纷；借款合同纠纷
私分国有资产
健康保险合同纠纷
侵害作品表演权纠纷
受贿
行政批准
船舶触碰损害责任纠纷
非法采矿；伪造公司、企业、事业单位、人民团体印章
执行判决、裁定滥用职权
装饰装修合同纠纷；建设工程合同纠纷
假冒注册商标
土地承包经营权转让合同纠纷
侮辱
商品房委托代理销售合同纠纷
建设工程施工合同纠纷；建设工程合同纠纷
申请承认与执行法院判决、仲裁裁决案件；交通肇事
占有保护纠纷
技术咨询合同纠纷
非国家工作人员受贿；枉法仲裁
抢劫；非法持有、私藏枪支、弹药
生产、销售假药
非法猎捕、杀害珍贵、濒危野生动物
人寿保险合同纠纷
行政裁决
监护权纠纷
申请变更监护人
城市公交运输合同纠纷
盗窃；抢夺
投放危险物质
非法采伐、毁坏国家重点保护植物
申请诉中财产保全；特殊程序
合同诈骗
计划生育行政管理（计划生育）
抢劫；强奸
盗掘古文化遗址、古墓葬
盗窃；破坏电力设备；掩饰、隐瞒犯罪所得、犯罪所得收益
滥用职权
公司解散纠纷
赌博
隐私权纠纷
盗窃；抢劫
申请诉中财产保全
组织考试作弊
经司法确认的调解协议
伪造货币
违法发放贷款
吸收客户资金不入账
过失致人死亡
强奸；抢劫
旅店服务合同纠纷
敲诈勒索；寻衅滋事
故意伤害；交通肇事
商标权权属纠纷
非国家工作人员受贿；挪用资金
拐卖妇女、儿童
非法狩猎
公司设立纠纷
抢劫；盗窃
没收财产
农业技术服务合同纠纷
故意伤害；寻衅滋事
行政登记
放火
请求撤销个别清偿行为纠纷
土地承包经营权转包合同纠纷
敲诈勒索；非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物
地面施工、地下设施损害责任纠纷
同业拆借纠纷
违法保全赔偿
著作权权属纠纷
申请诉前财产保全；特殊程序
其他（城建）
福利待遇纠纷
牧业承包合同纠纷
金融行政管理（金融）
请求公司收购股份纠纷
非法收购、运输盗伐、滥伐的林木
集资诈骗
抢夺
受贿；贪污
侵犯公民个人信息
走私、贩卖、运输、制造毒品；非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物
诈骗；敲诈勒索；伪造、变造、买卖国家机关公文、证件、印章；寻衅滋事；赌博
妨害信用卡管理
申请保全案件；其他案由
走私、贩卖、运输、制造毒品；容留他人吸毒
非法制造、销售非法制造的注册商标标识
脱逃；抢劫；强奸
故意伤害；引诱、容留、介绍卖淫
骗取出口退税；虚开增值税专用发票、用于骗取出口退税、抵扣税款发票
物件脱落、坠落损害责任纠纷
经济适用房转让合同纠纷
强迫卖淫；抢劫
公路旅客运输合同纠纷
非法种植毒品原植物
聚众扰乱社会秩序
骗取贷款、票据承兑、金融票证
倒卖文物
破坏电力设备
养老保险待遇纠纷
破坏广播电视设施、公用电信设施
伪造、变造、买卖身份证件
电力行政管理（电力）
出售、购买、运输假币
合伙协议纠纷；债权转让合同纠纷
因申请诉中财产保全损害责任纠纷
入伙纠纷
组织卖淫；协助组织卖淫
与公司、证券、保险、票据有关案件
物件损害责任纠纷
侵害作品发行权纠纷
侵害录音录像制作者权纠纷
追索劳动报酬纠纷；经济补偿金纠纷；工伤保险待遇纠纷
聚众斗殴；非法携带枪支、弹药、管制刀具、危险物品危及公共安全
虐待
票据纠纷
盗窃；放火
航次租船合同纠纷
非法携带枪支、弹药、管制刀具、危险物品危及公共安全
招标投标买卖合同纠纷
船舶融资租赁合同纠纷
拐卖妇女、儿童；重婚
强奸；盗窃
地质矿产行政管理（地矿）
寻衅滋事；开设赌场
走私、贩卖、运输、制造毒品；交通肇事
财产保险合同纠纷；其他案由
聚众斗殴；寻衅滋事
抢劫；强奸；盗窃；组织越狱
聚众斗殴；容留他人吸毒
邮寄服务合同纠纷
保险合同纠纷
申请认定财产无主
知识产权与竞争
组织、强迫、引诱、容留、介绍卖淫
林业行政管理（林业）
重大责任事故
借款合同纠纷；保证合同纠纷
审计行政管理（审计）
企业借贷纠纷；金融借款合同纠纷
相邻污染侵害纠纷
盗窃；走私、贩卖、运输、制造毒品
保险诈骗
刑事违法查封、扣押、冻结、追缴赔偿
相邻用水、排水纠纷
职务侵占；重婚；敲诈勒索
聚众淫乱
试用买卖合同纠纷
抢劫；绑架；强奸
诈骗；敲诈勒索
走私、贩卖、运输、制造毒品；绑架
抢夺；敲诈勒索
虚开增值税专用发票、用于骗取出口退税、抵扣税款发票；拒不支付劳动报酬
贷款诈骗
公司决议效力确认纠纷
抢夺；交通肇事
诈骗；故意伤害
诈骗；信用卡诈骗
寻衅滋事；聚众斗殴
公司减资纠纷
行政受理
故意伤害；掩饰、隐瞒犯罪所得、犯罪所得收益
挪用资金；诈骗
破坏易燃易爆设备
建筑设备租赁合同纠纷；租赁合同纠纷
走私、贩卖、运输、制造毒品；故意伤害
强迫卖淫
走私、贩卖、运输、制造毒品；非法持有毒品
统计行政管理（统计）
破坏生产经营
申请承认与执行法院判决、仲裁裁决案件；诈骗
引诱、容留、介绍卖淫；故意伤害；非法经营
绑架；寻衅滋事
行贿；受贿
招摇撞骗
交通肇事；非法占用农用地
强奸；故意伤害；盗窃
行政合同
水污染责任纠纷
企业出资人权益确认纠纷
失火
扰乱公共秩序
保险费纠纷
受贿；私分国有资产
组织、领导、参加黑社会性质组织
申请破产和解
技术合作开发合同纠纷
洗钱
非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物；抢劫
航空货物运输合同纠纷
抢劫；抢夺
破坏电力设备；盗窃
申请保全案件；因申请诉前财产保全损害责任纠纷
行贿
行政许可
强奸；猥亵儿童
诈骗；危险驾驶
介绍贿赂
合同诈骗；行贿
行政处罚；行政执行
植物新品种权权属纠纷；植物新品种权转让合同纠纷
非法收购、运输、出售珍贵、濒危野生动物、珍贵、濒危野生动物制品
消除危险纠纷
金融借款合同纠纷；借款合同纠纷
土地承包经营权确认纠纷
抢劫；寻衅滋事
工伤事故损害赔偿纠纷
故意毁坏财物；聚众斗殴；非法拘禁
用益物权确认纠纷
聚众斗殴；盗窃
证券虚假陈述责任纠纷
公路交通行政管理（公路）
故意毁坏财物；寻衅滋事
见义勇为人受害责任纠纷
相邻损害防免关系纠纷
分家析产纠纷；法定继承纠纷
故意伤害；盗窃
故意伤害；窝藏、包庇
抢劫；抢夺；交通肇事
行政执行
商标代理合同纠纷
盗窃；脱逃
敲诈勒索；寻衅滋事；妨害公务
抢劫；绑架；帮助毁灭、伪造证据
盗窃；破坏电力设备
非法拘禁；抢劫
抢劫枪支、弹药、爆炸物
抢劫；抢夺；盗窃
破坏监管秩序
擅自使用知名商品特有名称、包装、装潢纠纷
抵押权纠纷
诈骗；掩饰、隐瞒犯罪所得、犯罪所得收益
婚姻家庭、继承纠纷；离婚后财产纠纷
非法出售、提供试题、答案
公司债券交易纠纷
申请诉前财产保全；因申请诉前财产保全损害责任纠纷
信息电讯行政管理（信息、电讯）
委托代建合同纠纷
申请承认与执行法院判决、仲裁裁决案件；组织、领导、参加黑社会性质组织
房地产开发经营合同纠纷
建设工程合同纠纷；因申请诉前财产保全损害责任纠纷
盗窃；掩饰、隐瞒犯罪所得、犯罪所得收益
非法拘禁；抢劫；非法持有毒品
合同诈骗；盗窃；容留他人吸毒
债权债务概括转移合同纠纷
破坏易燃易爆设备；盗窃
故意毁坏财物；走私、贩卖、运输、制造毒品
生产、销售伪劣农药、兽药、化肥、种子
抢劫；盗窃；故意伤害
销售假冒注册商标的商品；诈骗
寻衅滋事；非法占用农用地
非法侵入住宅
破产撤销权纠纷
扰乱市场秩序
代位继承纠纷
行政案由
建设工程勘察合同纠纷
破坏计算机信息系统
体育行政管理（体育）
检验合同纠纷
妨害国境卫生检疫
寻衅滋事；盗窃
渔业行政管理（渔业）
脱逃；非法持有毒品
聚众斗殴；开设赌场
行政监察（监察）
寻衅滋事；妨害公务
道路交通事故人身损害赔偿纠纷
非法持有、私藏枪支、弹药；非法猎捕、杀害珍贵、濒危野生动物；非法狩猎
申请破产重整
专利权权属纠纷
演出合同纠纷
适用特殊程序案件案由；申请保全案件；申请诉前财产保全
生育保险待遇纠纷
人民调解协议纠纷
行政奖励
保险人代位求偿权纠纷；保险纠纷
非法购买增值税专用发票、购买伪造的增值税专用发票
修理、重作、更换纠纷
企业租赁经营合同纠纷
新增资本认购纠纷；买卖合同纠纷
侵害作品复制权纠纷
违法发放贷款；职务侵占
申请承认和执行外国法院民事判决、裁定
强奸；寻衅滋事
协助组织卖淫；寻衅滋事
盗窃；容留他人吸毒
申请保全案件；合同纠纷
过失致人重伤
挪用公款
船舶建造合同纠纷
建筑物区分所有权纠纷
申请承认与执行法院判决、仲裁裁决案件；故意伤害
走私、贩卖、运输、制造毒品；寻衅滋事
专利行政管理（专利）
销售假冒注册商标的商品
故意伤害；抢劫
走私、贩卖、运输、制造毒品；协助组织卖淫
抢劫；故意伤害
消防管理（消防）
海事海商
财政行政管理（财政）
非法处置查封、扣押、冻结的财产
赌博；倒卖文物
过失损坏电力设备
确认收养关系纠纷
融资租赁合同纠纷；因申请诉前财产保全损害责任纠纷
重大劳动安全事故
抢劫；故意杀人
生产、销售有毒、有害食品
走私、贩卖、运输、制造毒品；非法持有、私藏枪支、弹药
植物新品种实施许可合同纠纷
走私、贩卖、运输、制造毒品；非法持有、私藏枪支、弹药；故意伤害
教育行政管理（教育）
对下级法院执行异议裁定的复议
故意伤害；聚众斗殴；寻衅滋事
融资融券交易纠纷
庆典服务合同纠纷
职务侵占；盗窃
寻衅滋事；容留他人吸毒
交通肇事；盗窃
追索劳动报酬纠纷；经济补偿金纠纷
单位行贿
抢劫；盗窃；破坏电力设备
聚众冲击国家机关
盗窃；危险驾驶
盗窃、抢夺枪支、弹药、爆炸物
走私、贩卖、运输、制造毒品；容留他人吸毒；掩饰、隐瞒犯罪所得、犯罪所得收益
抢劫；走私、贩卖、运输、制造毒品
盗伐林木；滥伐林木
申请宣告公民无民事行为能力；申请确定监护人
伪证
侵害作品广播权纠纷
脱逃；抢劫；盗窃
畜牧行政管理（畜牧）
贪污；受贿
票据利益返还请求权纠纷；返还原物纠纷
联合运输合同纠纷
帮助犯罪分子逃避处罚；受贿；诈骗
走私、贩卖、运输、制造毒品；抢劫
合同诈骗；信用卡诈骗
抢劫；抢夺；盗窃；诈骗
污染环境
倒卖车票、船票
故意伤害；危险驾驶
抢劫；诈骗
故意毁坏财物；非法拘禁
聚众斗殴；抢劫
再审无罪赔偿
盗窃；强奸
寻衅滋事；窝藏、包庇
抢劫；窝藏、转移、收购、销售赃物
采矿权转让合同纠纷
伪造公司、企业、事业单位、人民团体印章
民间借贷纠纷；企业借贷纠纷
爆炸
非法采伐、毁坏国家重点保护植物；盗伐林木
盗窃；盗伐林木
抢劫；盗窃；强奸
强奸；强制猥亵、侮辱妇女
合伙企业纠纷
行政强制；行政执行
寻衅滋事；故意伤害
用人单位责任纠纷
冒充军人招摇撞骗
民间借贷纠纷；不动产登记纠纷
盗窃；诈骗
寻衅滋事；非法拘禁；非法搜查；串通投标；伪造、变造、买卖国家机关公文、证件、印章；容留他人吸毒；诈骗；故意毁坏财物
业主共有权纠纷
走私国家禁止进出口的货物、物品；走私普通货物、物品
包庇、纵容黑社会性质组织
小额借款合同纠纷；商品房预售合同纠纷
行政命令
行政规划
互易纠纷
公司债券回购合同纠纷
合同纠纷；民间借贷纠纷
故意伤害；强奸；破坏广播电视设施、公用电信设施
执行异议之诉；案外人执行异议之诉
代替考试
挪用公款；受贿；单位行贿
诈骗；窃取、收买、非法提供信用卡信息
非法生产、买卖、运输制毒物品、走私制毒物品
强奸；非法拘禁；敲诈勒索
非法经营；非法持有、私藏枪支、弹药
公司分立纠纷
容留他人吸毒；合同诈骗
合同诈骗；寻衅滋事
申请保全案件；申请诉前财产保全
故意伤害；抢劫；掩饰、隐瞒犯罪所得、犯罪所得收益
其他（交通）
支付令
抢劫；敲诈勒索；寻衅滋事；容留他人吸毒
高度危险责任纠纷
侵害计算机软件著作权纠纷
抢劫；强制猥亵、侮辱妇女
违法司法拘留赔偿
抢劫；强奸；破坏交通设施
国内涉外仲裁裁决
猥亵儿童；强奸
相邻采光、日照纠纷
金融不良债权转让合同纠纷
职工破产债权确认纠纷
非法拘禁；强奸
抢劫；盗窃；寻衅滋事
非国家工作人员受贿；贪污；职务侵占
公司关联交易损害责任纠纷
帮助毁灭、伪造证据
房屋买卖合同纠纷；机动车交通事故责任纠纷
股权质权纠纷
故意杀人；盗窃
抢劫；非法拘禁
非法持有毒品；非法持有、私藏枪支、弹药；容留他人吸毒
强迫卖淫；抢劫；强奸
强迫卖淫；过失致人死亡；非法拘禁
绑架；抢劫
故意杀人；走私、贩卖、运输、制造毒品
破坏电力设备；抢劫；盗窃
申请撤销监护人资格
妨害作证
走私、贩卖、运输、制造毒品；盗窃
走私普通货物、物品
合同纠纷；劳动争议
侵害患者知情同意权责任纠纷
侵害植物新品种权纠纷
追收未缴出资纠纷；股东出资纠纷
工商行政管理（工商）
票据诈骗
抢劫；强奸；敲诈勒索
侵害作品复制权纠纷；侵害作品发行权纠纷
非法持有毒品；走私、贩卖、运输、制造毒品；故意伤害
故意伤害；破坏电力设备
盗窃；故意伤害
走私废物
医疗损害赔偿纠纷
合同诈骗；诈骗
拍卖合同纠纷
逃税
合同纠纷；金融借款合同纠纷
挪用公款；贪污
抢劫；强迫他人吸毒
食品药品安全行政管理（食品、药品）
行贿；对非国家工作人员行贿
著作权合同纠纷
与破产有关的纠纷；破产债权确认纠纷
票据利益返还请求权纠纷
行政允诺
爆炸；职务侵占
特殊程序
强迫卖淫；引诱、容留、介绍卖淫；强奸
寻衅滋事；抢劫
受贿；单位受贿
诬告陷害
票据损害责任纠纷
信用卡纠纷；商品房销售合同纠纷
危害公共安全
绑架；抢劫；敲诈勒索
合伙协议纠纷；委托合同纠纷
强制猥亵、侮辱妇女；抢劫
盗窃；妨害公务
抢劫；绑架
强奸；引诱、容留、介绍卖淫
强奸；抢劫；盗窃
建设工程价款优先受偿权纠纷
先予执行
伪造、变造居民身份证
挪用公款；巨额财产来源不明；贪污
破坏社会主义市场经济秩序
土壤污染责任纠纷
故意伤害；开设赌场
盗窃；抢劫；强奸
盗掘古人类化石、古脊椎动物化石；倒卖文物
失职致使在押人员脱逃
追收抽逃出资纠纷；股东出资纠纷
彩票、奖券纠纷
故意杀人；放火
职务侵占；伪造公司、企业、事业单位、人民团体印章
绑架；盗窃
金融诈骗
排除妨害纠纷；恢复原状纠纷
非法持有毒品；容留他人吸毒
受贿；滥用职权
寻衅滋事；赌博
强奸；盗窃；故意伤害
受贿；国有公司、企业、事业单位人员滥用职权；滥用职权
侵害其他著作财产权纠纷
贪污；受贿；滥用职权
组织、领导、参加黑社会性质组织；故意伤害；抢劫；故意毁坏财物；寻衅滋事
故意伤害；走私、贩卖、运输、制造毒品
绑架；诈骗
故意伤害；故意毁坏财物
故意杀人；抢劫；盗窃
专利代理合同纠纷
合同、无因管理、不当得利纠纷；合同纠纷；借款合同纠纷；民间借贷纠纷
遗失物返还纠纷
骗取出口退税
脱逃
放火；强奸
肖像权纠纷；名誉权纠纷
掩饰、隐瞒犯罪所得、犯罪所得收益；伪造、变造居民身份证
强迫交易；敲诈勒索；故意毁坏财物；寻衅滋事；破坏生产经营
辞退争议
行政救助
交通肇事；伪造、变造、买卖国家机关公文、证件、印章
污染环境；寻衅滋事；挪用公款
故意伤害；拐卖妇女、儿童
组织卖淫；走私、贩卖、运输、制造毒品
小额借款合同纠纷；企业借贷纠纷
绑架；强奸
信用卡诈骗；诈骗
组织卖淫；抢劫
非法狩猎；掩饰、隐瞒犯罪所得、犯罪所得收益
申请保全案件；买卖合同纠纷
非法买卖制毒物品
强奸；故意伤害；抢劫；盗窃
诈骗；盗窃；危险驾驶
寻衅滋事；危险驾驶
盐业行政管理（盐业）
对外国公职人员、国际公共组织官员行贿
传播淫秽物品
非国家工作人员受贿；职务侵占；挪用资金
提供侵入、非法控制计算机信息系统程序、工具
使用虚假身份证件、盗用身份证件
股票交易纠纷
组织、领导、参加黑社会性质组织；故意毁坏财物；寻衅滋事
诈骗；敲诈勒索；赌博；寻衅滋事
故意杀人；强奸
其他（农业）
申请撤销宣告失踪
挪用公款；盗窃
过失致人死亡；窝藏、包庇
财产保险合同纠纷；机动车交通事故责任纠纷
贪污；职务侵占
走私珍贵动物、珍贵动物制品
职务侵占；诈骗
盗窃；非法持有毒品
职务侵占；寻衅滋事
抢夺；盗窃
经济补偿金纠纷；追索劳动报酬纠纷
伪造、变造金融票证
商业诋毁纠纷
车位纠纷
危险驾驶；故意伤害
国有公司、企业、事业单位人员失职
职务侵占；非国家工作人员受贿
非法持有、私藏枪支、弹药；盗窃
非法转让、倒卖土地使用权
诈骗；合同诈骗；伪造、变造、买卖国家机关公文、证件、印章；伪造公司、企业、事业单位、人民团体印章；伪造、变造居民身份证；妨害信用卡管理
无因管理纠纷；不当得利纠纷
敲诈勒索；诈骗
追收抽逃出资纠纷
抢劫；破坏电力设备；破坏广播电视设施、公用电信设施；盗窃
贪污；挪用公款
非法拘禁；开设赌场
扰乱国家机关工作秩序
生命权、健康权、身体权纠纷；财产损害赔偿纠纷
盗窃；故意毁坏财物
强迫交易；开设赌场
运输合同纠纷；租赁合同纠纷
盗窃；寻衅滋事
诈骗；非法拘禁；敲诈勒索
破坏广播电视设施、公用电信设施；盗窃
走私、贩卖、运输、制造毒品；故意伤害；寻衅滋事
持有、使用假币
民间借贷纠纷；金融借款合同纠纷
危险驾驶；重大责任事故
合伙企业财产份额转让纠纷
国有资产行政管理（国资）
聚众斗殴；走私、贩卖、运输、制造毒品
申请保全案件；追偿权纠纷
受贿；帮助犯罪分子逃避处罚
知识产权与竞争纠纷
职务侵占；掩饰、隐瞒犯罪所得、犯罪所得收益
监护人责任纠纷
申请诉前证据保全
申请保全案件；海事诉讼特别程序案件
申请承认与执行法院判决、仲裁裁决案件；走私、贩卖、运输、制造毒品
失业保险待遇纠纷
土地承包经营权纠纷；承包地征收补偿费用分配纠纷
贪污；职务侵占；非国家工作人员受贿
假冒专利
监护权特别程序案件
小额借款合同纠纷；企业借贷纠纷；金融借款合同纠纷
取回权纠纷
强迫卖淫；强奸
行政行为
测试合同纠纷
海事海商纠纷
开设赌场；寻衅滋事
经贸行政管理（内贸、外贸）
保险诈骗；寻衅滋事；危险驾驶
非法制造、买卖、运输、储存危险物质
盗窃、侮辱、故意毁坏尸体、尸骨、骨灰
编造、故意传播虚假信息
最高额抵押权纠纷
故意伤害；寻衅滋事；开设赌场
拐卖妇女、儿童；强迫卖淫
寻衅滋事；敲诈勒索
赌博；拒不支付劳动报酬
贪污；受贿；巨额财产来源不明
信用保险合同纠纷
非法持有、私藏枪支、弹药；聚众斗殴；寻衅滋事
物权保护纠纷；返还原物纠纷
单位行贿；行贿
诈骗；容留他人吸毒
故意伤害；妨害公务
掩饰、隐瞒犯罪所得、犯罪所得收益；诈骗
聚众斗殴；非法拘禁；寻衅滋事
窝藏、转移、隐瞒毒品、毒赃
借记卡纠纷
医疗产品责任纠纷
申请拍卖扣押船舶
掩饰、隐瞒犯罪所得、犯罪所得收益；非法采矿
对非国家工作人员行贿
危险驾驶；妨害公务
侵犯商业秘密
侵害表演者权纠纷
合同、无因管理、不当得利纠纷；合同纠纷；金融借款合同纠纷
拐卖妇女、儿童；抢劫
申请撤销宣告公民死亡
非法拘禁；危险驾驶
危险物品肇事
非法持有、私藏枪支、弹药；寻衅滋事；赌博；开设赌场；故意伤害
强奸；诈骗
房屋租赁合同纠纷；物业服务合同纠纷
寻衅滋事；职务侵占
文化行政管理（文化）
烟草专卖行政管理（烟草专卖）
邮政行政管理（邮政）
包庇毒品犯罪分子
单位受贿；单位行贿；贪污；受贿；挪用公款；国有公司、企业、事业单位人员滥用职权；滥用职权
动植物检疫徇私舞弊
协助组织卖淫；强迫卖淫
非法利用信息网络
船舶营运借款合同纠纷
申请保全案件；借款合同纠纷
帮助信息网络犯罪活动
申请认可和执行澳门特别行政区法院民事判决
贪污；行贿
侵犯著作权
非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物；危险驾驶
交通肇事；窝藏、包庇
抢劫；强制猥亵、侮辱妇女；故意杀人
故意伤害；故意毁坏财物；妨害作证
敲诈勒索；强迫交易
追索劳动报酬纠纷；劳动争议
假冒注册商标；销售假冒注册商标的商品
非法拘禁；寻衅滋事
聚众斗殴；故意伤害
故意伤害；非法拘禁
受贿；为亲友非法牟利
单位受贿；贪污
侵犯公民人身权利、民主权利
徇私枉法；受贿
铁路修建合同纠纷
盗窃；掩饰、隐瞒犯罪所得、犯罪所得收益；强奸
非法获取计算机信息系统数据、非法控制计算机信息系统
申请扣押船舶
合伙协议纠纷；股权转让纠纷
非法收购、运输、加工、出售国家重点保护植物、国家重点保护植物制品
挪用公款；受贿
编造、故意传播虚假恐怖信息
行政征收；行政处罚
展览合同纠纷
群众性活动组织者责任纠纷
挪用资金；非国家工作人员受贿
合伙协议纠纷；劳动合同纠纷
盗窃；伪造、变造居民身份证
聚众扰乱公共场所秩序、交通秩序
合伙协议纠纷；申请公司清算
诈骗；挪用公款
受贿；徇私枉法
排除妨害纠纷；物件损害责任纠纷
盗窃；非法采伐、毁坏国家重点保护植物
行贿；非法采矿
申请承认与执行法院判决、仲裁裁决案件；盗窃
强迫劳动
战时造谣惑众
小额借款合同纠纷；金融借款合同纠纷
寻衅滋事；诈骗
贪污；职务侵占；挪用资金
敲诈勒索；寻衅滋事；非法占用农用地
寻衅滋事；伪造、变造居民身份证
绑架；出售、购买、运输假币
侵犯公民人身权利、民主权利；故意伤害
合同、无因管理、不当得利纠纷；侵权责任纠纷
证券投资基金交易纠纷
业主专有权纠纷
医疗保险待遇纠纷
受贿；掩饰、隐瞒犯罪所得、犯罪所得收益
非法获取公民个人信息
探矿权转让合同纠纷
适用特殊程序案件案由；仲裁程序案件
荣誉权纠纷
非法持有毒品；窝藏、包庇
侵害出版者权纠纷
组织、领导、参加黑社会性质组织；妨害公务；聚众冲击国家机关；聚众斗殴
危害公共安全；危险驾驶
侵犯财产
重审无罪赔偿
返还原物纠纷；租赁合同纠纷
受贿；诬告陷害
聚众斗殴；抢劫；走私、贩卖、运输、制造毒品；故意伤害
养殖权纠纷
分家析产纠纷；遗嘱继承纠纷
附义务赠与合同纠纷
故意伤害；聚众斗殴
合同、无因管理、不当得利纠纷；合同纠纷；建设工程合同纠纷
猥亵儿童；寻衅滋事
聚众斗殴；故意伤害；盗窃
走私、贩卖、运输、制造毒品；洗钱
引诱、教唆、欺骗他人吸毒
容留他人吸毒；诈骗
徇私舞弊减刑、假释、暂予监外执行
婚姻家庭、继承纠纷；婚姻家庭纠纷；离婚后财产纠纷
传授犯罪方法
证券纠纷
申请保全案件；申请承认与执行法院判决、仲裁裁决案件
能源行政管理（能源管理）
重大责任事故；伪造公司、企业、事业单位、人民团体印章
撤销婚姻纠纷
转质权纠纷
与公司、证券、保险、票据等有关的民事纠纷；与破产有关的纠纷；申请破产清算
排除妨害纠纷；返还原物纠纷
贪污；诈骗
房屋租赁合同纠纷；确认劳动关系纠纷
故意杀人；抢劫；合同诈骗；诈骗
追偿权纠纷；保证合同纠纷
无罪逮捕赔偿
法定继承纠纷；共有纠纷
伪造、变造、买卖国家机关公文、证件、印章；伪造公司、企业、事业单位、人民团体印章；伪造、变造居民身份证
抢劫；容留他人吸毒
伪造、倒卖伪造的有价票证
非法持有毒品；持有、使用假币
走私制毒物品
商标使用许可合同纠纷
开设赌场；赌博
遗嘱继承纠纷；法定继承纠纷
营业信托纠纷
危险驾驶；交通肇事
海上、通海水域人身损害责任纠纷
非法侵入计算机信息系统
挂靠经营合同纠纷；委托合同纠纷
强迫卖淫；强奸；抢劫
诈骗；寻衅滋事；赌博；骗取贷款、票据承兑、金融票证
申请保全案件；租赁合同纠纷
诈骗；伪造、变造、买卖国家机关公文、证件、印章；伪造、变造居民身份证
诈骗；抢夺
妨害动植物防疫、检疫
林木折断损害责任纠纷
合同、无因管理、不当得利纠纷；合同纠纷；建设工程合同纠纷；建设工程分包合同纠纷
证券回购合同纠纷
督促程序案件
合同、无因管理、不当得利纠纷；合同纠纷；买卖合同纠纷
组织、领导、参加黑社会性质组织；抢劫；寻衅滋事；敲诈勒索
故意伤害；聚众斗殴；故意毁坏财物；寻衅滋事
法定继承纠纷；遗嘱继承纠纷
抢夺；抢劫
非法获取计算机信息系统数据、非法控制计算机信息系统；传授犯罪方法
拒不执行判决、裁定；遗弃
拐卖妇女、儿童；抢劫；敲诈勒索；寻衅滋事
非法持有、私藏枪支、弹药；非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物
脱逃；盗窃
妨害公务；危险驾驶
放火；故意毁坏财物
船舶买卖合同纠纷
债权纠纷
小额借款合同纠纷；民间借贷纠纷
强奸；组织未成年人进行违反治安管理活动
容留他人吸毒；走私、贩卖、运输、制造毒品
故意伤害；盗窃；抢劫
遗赠纠纷；遗嘱继承纠纷
盗窃、抢夺枪支、弹药、爆炸物、危险物质
港口作业纠纷
敲诈勒索；寻衅滋事；窝藏、包庇
赌博；寻衅滋事
行政执行；其他行政行为
技术转让合同纠纷
侵害商业秘密纠纷
铁路行政管理（铁路）
寻衅滋事；强迫交易
项目转让合同纠纷
组织淫秽表演
知识产权合同纠纷
重大责任事故；过失致人死亡
信用卡纠纷；金融借款合同纠纷
寻衅滋事；聚众斗殴；故意毁坏财物
走私、贩卖、运输、制造毒品；盗窃；掩饰、隐瞒犯罪所得、犯罪所得收益
受贿；行贿
港口货物保管合同纠纷
船舶抵押合同纠纷
伪造、变造、买卖国家机关公文、证件、印章；伪造、变造居民身份证
合同、无因管理、不当得利纠纷；合同纠纷；借款合同纠纷
非法采矿；非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物
小额借款合同纠纷；所有权确认纠纷
商标权权属纠纷；商标权转让合同纠纷
合同、无因管理、不当得利纠纷；合同纠纷；建设工程合同纠纷；建设工程施工合同纠纷
法定继承纠纷；分家析产纠纷
信用证纠纷
故意伤害；抢劫；盗窃
伪造、变造居民身份证；危险驾驶
民间借贷纠纷；房屋租赁合同纠纷
合作创作合同纠纷
诈骗；保险诈骗
故意伤害；合同诈骗
妨害社会管理秩序
海上、通海水域财产损害责任纠纷
申请承认与执行法院判决、仲裁裁决案件；贪污；受贿；挪用公款；徇私舞弊低价折股、出售国有资产
抢劫；抢夺；盗窃；故意伤害
挪用公款；贪污；受贿
非法拘禁；非法持有毒品
合同、无因管理、不当得利纠纷；合同纠纷
诈骗；敲诈勒索；寻衅滋事
非法吸收公众存款；合同诈骗；挪用资金
申请撤销调解确认决定
抢劫；抢夺；敲诈勒索
故意杀人；诈骗
走私淫秽物品
运输合同纠纷；买卖合同纠纷
强奸；故意杀人
放纵制售伪劣商品犯罪行为
合同、无因管理、不当得利纠纷；合同纠纷；承揽合同纠纷
故意伤害；寻衅滋事；强迫交易
贪污；受贿；行贿
运输合同纠纷；劳务合同纠纷；买卖合同纠纷
非法收购、运输、出售珍贵、濒危野生动物、珍贵、濒危野生动物制品；非法狩猎
证券托管纠纷
铁路运输人身损害责任纠纷
股票权利确认纠纷
强奸；拐骗儿童
拐卖妇女、儿童；收买被拐卖的妇女、儿童
强奸；强迫卖淫
虐待被监护、看护人
放火；寻衅滋事
故意杀人；非法拘禁
抢劫；掩饰、隐瞒犯罪所得、犯罪所得收益
医疗损害责任纠纷；机动车交通事故责任纠纷
遗嘱继承纠纷；分家析产纠纷
高利转贷
破产债权确认纠纷；保证合同纠纷
民事；建设工程施工合同纠纷
绑架；走私、贩卖、运输、制造毒品
抢劫；故意伤害；诈骗
企业债权转股权合同纠纷
海关行政管理（海关）
共同海损纠纷
故意杀人；盗窃；窝藏、转移、收购、销售赃物
骗取贷款、票据承兑、金融票证；诈骗
申请确定监护人；申请宣告公民无民事行为能力
组织、资助非法聚集
合同、无因管理、不当得利纠纷；合同纠纷；借款合同纠纷；金融借款合同纠纷
技术培训合同纠纷
走私、贩卖、运输、制造毒品；掩饰、隐瞒犯罪所得、犯罪所得收益
拒不执行判决、裁定；非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物
非法采矿；故意伤害
金融委托理财合同纠纷
公司合并纠纷
船舶租用合同纠纷
窃取、收买、非法提供信用卡信息；掩饰、隐瞒犯罪所得、犯罪所得收益
非法收购、运输、出售珍贵、濒危野生动物、珍贵、濒危野生动物制品；诈骗
商标合同纠纷
申请实现担保物权案件
故意伤害；非法持有、私藏枪支、弹药
船舶碰撞损害责任纠纷
传授犯罪方法；诈骗
敲诈勒索；寻衅滋事；非法持有、私藏枪支、弹药
包庇、纵容黑社会性质组织；高利转贷
商品房预售合同纠纷；商品房销售合同纠纷
非法经营；开设赌场
走私、贩卖、运输、制造毒品；非法拘禁
非法猎捕、杀害珍贵、濒危野生动物；非法收购、运输、出售珍贵、濒危野生动物、珍贵、濒危野生动物制品
非法生产、买卖警用装备
房屋买卖合同纠纷；买卖合同纠纷
煽动民族仇恨、民族歧视
提供虚假证明文件
不明抛掷物、坠落物损害责任纠纷
非法采伐、毁坏国家重点保护植物；滥伐林木
资源行政管理
买卖合同纠纷；保证合同纠纷
法定继承纠纷；物权确认纠纷
合同诈骗；敲诈勒索
返还原物纠纷；排除妨害纠纷
拐骗儿童
广告合同纠纷；承揽合同纠纷
招摇撞骗；诈骗
强奸；抢劫；聚众斗殴；寻衅滋事
聚众斗殴；敲诈勒索；寻衅滋事；破坏生产经营
签订、履行合同失职
非法猎捕、杀害珍贵、濒危野生动物；非法占用农用地
劳务合同纠纷；债权转让合同纠纷
敲诈勒索；诈骗；寻衅滋事
抢夺；掩饰、隐瞒犯罪所得、犯罪所得收益
故意伤害；强迫交易
滥用职权；受贿；单位受贿
对单位行贿
非法经营同类营业
开设赌场；窝藏、包庇
走私、贩卖、运输、制造毒品；诈骗
非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物；非法持有、私藏枪支、弹药；抢劫
计算机软件著作权权属纠纷；计算机软件著作权许可使用合同纠纷
保险代理合同纠纷
临时用地合同纠纷
合同、无因管理、不当得利纠纷；合同纠纷；追偿权纠纷
隐瞒、掩饰犯罪所得、犯罪所得收益
聚众斗殴；聚众扰乱社会秩序
伪造、变造、买卖武装部队公文、证件、印章
盗窃；伪造、变造、买卖国家机关公文、证件、印章
招摇撞骗；诈骗；盗窃
走私
分家析产纠纷；法定继承纠纷；遗嘱继承纠纷
合同诈骗；故意毁坏财物
非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物；非法持有、私藏枪支、弹药
房地产价格评估合同纠纷
申请保全案件；运输合同纠纷
故意伤害；敲诈勒索
家政服务合同纠纷；金融借款合同纠纷
容留他人吸毒；盗窃
侵害企业出资人权益纠纷
借款合同纠纷；金融借款合同纠纷
非法拘禁；容留他人吸毒
盗窃；抢劫；掩饰、隐瞒犯罪所得、犯罪所得收益
买卖合同纠纷；债权转让合同纠纷
农业承包合同纠纷；确认合同效力纠纷
集资诈骗；非法吸收公众存款
抢劫；脱逃
证券投资咨询纠纷
协助送达司法文书和调查取证
假冒注册商标；生产、销售伪劣产品
贪污；盗窃
买卖合同纠纷；因申请诉前财产保全损害责任纠纷
抢劫；强奸；盗窃
生命权、健康权、身体权纠纷；机动车交通事故责任纠纷
分家析产纠纷；遗嘱继承纠纷；法定继承纠纷
占有、使用高度危险物损害责任纠纷
强奸；抢劫；诈骗；敲诈勒索
故意杀人；盗窃、侮辱尸体
保安服务合同纠纷；房屋租赁合同纠纷
乡政府；行政强制
盗窃；破坏电力设备；强奸；抢劫
刑讯逼供致伤、致死赔偿
伪造货币；持有、使用假币
诈骗；票据诈骗
走私、贩卖、运输、制造毒品；容留他人吸毒；寻衅滋事
故意杀人；贪污；敲诈勒索
受贿；包庇、纵容黑社会性质组织；非法持有、私藏枪支、弹药；侵犯公民个人信息
强迫卖淫；引诱、容留、介绍卖淫
贪污；受贿；挪用公款
放射性污染责任纠纷
侮辱；诽谤
非国家工作人员受贿；对非国家工作人员行贿
建设工程合同纠纷；排除妨害纠纷
申请承认与执行法院判决、仲裁裁决案件；申请保全案件
分期付款买卖合同纠纷；民间借贷纠纷
窃取、收买、非法提供信用卡信息；信用卡诈骗
盗窃；破坏广播电视设施、公用电信设施
拐卖妇女、儿童；盗窃
故意伤害；盗窃；聚众斗殴
走私、贩卖、运输、制造毒品；非法持有毒品；容留他人吸毒
妨害公务；故意伤害
交通肇事；故意毁坏财物
虚开增值税专用发票、用于骗取出口退税、抵扣税款发票；容留他人吸毒
合同、无因管理、不当得利纠纷；合同纠纷；租赁合同纠纷；房屋租赁合同纠纷
抢劫；强奸；绑架
认定财产无主案件
盗窃；窝藏、包庇
著作权权属、侵权纠纷；商业贿赂不正当竞争纠纷
故意伤害；盗窃；敲诈勒索
诈骗；交通肇事
组织考试作弊；代替考试
窝藏、转移、收购、销售赃物
故意伤害；组织卖淫
利用影响力受贿
故意伤害；诈骗
走私、贩卖、运输、制造毒品；抢夺
与公司、证券、保险、票据等有关的民事纠纷；与公司有关的纠纷；股权转让纠纷
强奸；绑架；抢劫
放火；敲诈勒索；盗窃
房屋买卖合同纠纷；居间合同纠纷
非法持有、私藏枪支、弹药；非法狩猎
应收账款质权纠纷
侵害经营秘密纠纷
水路货物运输合同纠纷
妨害信用卡管理；信用卡诈骗
抢劫；盗窃；掩饰、隐瞒犯罪所得、犯罪所得收益
危险驾驶；寻衅滋事
受贿；滥用职权；破坏计算机信息系统
非法制造、出售非法制造的发票
国际货物买卖合同纠纷
信用卡诈骗；伪造公司、企业、事业单位、人民团体印章
非法经营；窝藏、包庇
擅自发行股票、公司、企业债券；合同诈骗
过失损坏广播电视设施、公用电信设施
走私、贩卖、运输、制造毒品；非法买卖、运输、携带、持有毒品原植物种子、幼苗
合伙协议纠纷；提供劳务者受害责任纠纷
船舶检验合同纠纷；承揽合同纠纷
名誉权纠纷；肖像权纠纷；隐私权纠纷
贷款诈骗；信用卡诈骗
新增资本认购纠纷
强奸；故意毁坏财物；抢劫
海难救助合同纠纷
海域使用权纠纷
过失致人死亡；非法拘禁
抢劫；强迫卖淫
破坏电力设备；盗窃；抢劫
故意杀人；故意伤害；招摇撞骗
行政征用
非法生产、销售专用间谍器材、窃听、窃照专用器材
信用卡诈骗；伪造、变造、买卖国家机关公文、证件、印章
强奸；妨害公务
抢劫；故意伤害；故意毁坏财物
挪用公款；职务侵占
违规制造、销售枪支
组织、领导、参加黑社会性质组织；开设赌场；寻衅滋事；强迫交易；组织卖淫
抢劫；寻衅滋事；故意毁坏财物
伪造、变造、买卖国家机关公文、证件、印章；盗窃
故意伤害；强奸
帮助犯罪分子逃避处罚
诈骗；污染环境；虚开增值税专用发票、用于骗取出口退税、抵扣税款发票；对非国家工作人员行贿；伪造公司、企业、事业单位、人民团体印章
抢劫；故意毁坏财物
走私、贩卖、运输、制造毒品；脱逃；容留他人吸毒
非法持有毒品；非法持有、私藏枪支、弹药
故意伤害；强奸；非法拘禁
聚众扰乱社会秩序；妨害公务
非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物；非法收购、运输、出售珍贵、濒危野生动物、珍贵、濒危野生动物制品
绑架；抢劫；强制猥亵、侮辱妇女
骗取出境证件
盗窃；破坏易燃易爆设备
申请认可和执行香港特别行政区法院民事判决
破坏电力设备；走私、贩卖、运输、制造毒品
非法持有毒品；非法买卖、运输、携带、持有毒品原植物种子、幼苗
侵犯著作权；掩饰、隐瞒犯罪所得、犯罪所得收益
破坏电力设备；诈骗；盗窃
强迫卖淫；强奸；故意伤害
生产、销售有毒、有害食品；生产、销售假药；行贿
强奸；抢劫；妨害公务
虐待被监管人
盗窃；敲诈勒索；诈骗
非法拘禁；敲诈勒索
抢劫；故意伤害；寻衅滋事
抢劫；盗窃；非法持有、私藏枪支、弹药
故意伤害；非法持有毒品
保安服务合同纠纷；民间借贷纠纷
合同诈骗；虚假出资、抽逃出资
走私、贩卖、运输、制造毒品；非法买卖制毒物品
寻衅滋事；放火；非法持有、私藏枪支、弹药；走私、贩卖、运输、制造毒品
走私普通货物、物品；走私废物
危险驾驶；盗窃
故意杀人；抢劫；奸淫幼女
罚金；追缴违法所得
走私、贩卖、运输、制造毒品；抢劫；抢夺
行政处罚；行政征收
盗窃；抢劫；聚众斗殴
非法生产、销售间谍专用器材
诈骗；侵占
强奸；寻衅滋事；故意伤害
非法吸收公众存款；集资诈骗
合同纠纷；借款合同纠纷
强迫交易；抢劫；盗窃
故意毁坏财物；赌博
租赁合同纠纷；保证合同纠纷
敲诈勒索；非法拘禁
抢劫；非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物
高利转贷；诈骗；寻衅滋事
故意伤害；盗窃；非法持有、私藏枪支、弹药
故意杀人；抢劫
窝藏、包庇；包庇毒品犯罪分子
故意伤害；寻衅滋事；敲诈勒索；强迫交易
职务侵占；合同诈骗
组织、领导、参加黑社会性质组织；寻衅滋事；聚众扰乱社会秩序；盗窃；故意伤害；容留他人吸毒
故意毁坏财物；故意伤害
交通肇事；危险驾驶
组织、领导、参加黑社会性质组织；故意伤害；走私、贩卖、运输、制造毒品
绑架；故意伤害
申请保全案件；申请承认与执行法院判决、仲裁裁决案件；因申请诉前财产保全损害责任纠纷
海上、通海水域养殖损害责任纠纷
寻衅滋事；非法持有毒品
生产、销售伪劣产品；职务侵占
盗窃；破坏电力设备；抢劫
破坏交通设施
合伙协议纠纷；承揽合同纠纷
期货交易纠纷
虚开增值税专用发票、用于骗取出口退税、抵扣税款发票；盗窃
故意杀人；故意伤害；故意毁坏财物
寻衅滋事；非法拘禁；故意伤害
海洋开发利用纠纷
非法经营；伪造、变造、买卖国家机关公文、证件、印章
水上运输损害责任纠纷
不当得利纠纷；无因管理纠纷
妨碍诉讼行为制裁决定、民事违法制裁决定
故意伤害；非法拘禁；寻衅滋事；非法持有、私藏枪支、弹药
非法采矿；掩饰、隐瞒犯罪所得、犯罪所得收益
知识产权合同纠纷；劳动争议
出版者权权属纠纷
合同纠纷；建设工程施工合同纠纷
容留他人吸毒；非法持有、私藏枪支、弹药；盗窃
故意杀人；盗窃；抢劫
运输合同纠纷；合伙协议纠纷；挂靠经营合同纠纷
妨害公务；聚众扰乱公共场所秩序、交通秩序
开设赌场；故意伤害
强奸；放火
危险驾驶；故意毁坏财物
赌博；聚众斗殴；非法拘禁
危险驾驶；诈骗
民间借贷纠纷；义务帮工人受害责任纠纷
故意毁坏财物；妨害作证
诈骗；窝藏、包庇
贪污；滥用职权
海事债权确权纠纷
同居关系析产、子女抚养纠纷
故意毁坏财物；传播淫秽物品
受贿；巨额财产来源不明
组织、领导、参加黑社会性质组织；敲诈勒索；强迫交易；聚众扰乱社会秩序；破坏生产经营；寻衅滋事
抢劫；盗窃；抢夺
奸淫幼女
知识产权合同纠纷；合同纠纷
宣扬恐怖主义、极端主义、煽动实施恐怖活动
伪造、变造、买卖国家机关公文、证件、印章；伪造、变造、买卖武装部队公文、证件、印章
收养关系纠纷
诈骗；职务侵占
非法吸收公众存款；合同诈骗
滥用职权；诈骗
引诱、容留、介绍卖淫；聚众斗殴
仲裁程序案件；申请确认仲裁协议效力
合同诈骗；拒不执行判决、裁定
盗窃；信用卡诈骗
船舶权属纠纷
敲诈勒索；故意伤害
妨害公务；敲诈勒索
寻衅滋事；敲诈勒索；非法拘禁
走私武器、弹药
扰乱无线电通讯管理秩序
保险诈骗；寻衅滋事
工伤保险待遇纠纷；经济补偿金纠纷
强迫交易；寻衅滋事
骗购外汇
证券交易合同纠纷
寻衅滋事；非法侵入住宅
诈骗；招摇撞骗
伪造货币；出售、购买、运输假币
建设工程施工合同纠纷；劳务合同纠纷
人身自由权纠纷；名誉权纠纷
受贿；贪污；国有公司、企业、事业单位人员滥用职权
职务侵占；贪污
集资诈骗；伪造、变造、买卖国家机关公文、证件、印章
音像制品制作合同纠纷
劳动争议、人事争议；劳动争议
别除权纠纷
信用卡诈骗；妨害信用卡管理；窃取、收买、非法提供信用卡信息
走私、贩卖、运输、制造毒品；赌博
故意毁坏财物；非法侵入住宅
诈骗；寻衅滋事
诈骗；非法拘禁
组织未成年人进行违反治安管理活动
采矿权纠纷
非法拘禁；故意伤害
伪造、盗窃、买卖、非法提供、非法使用武装部队专用标志
受贿；贪污；赌博
非法种植毒品原植物；非法持有、私藏枪支、弹药
动植物检疫徇私舞弊；受贿
强奸；交通肇事
诈骗；非法经营
盗窃；掩饰、隐瞒犯罪所得、犯罪所得收益；破坏电力设备；窝藏、转移、收购、销售赃物
婚姻家庭、继承纠纷；婚姻家庭纠纷
危险驾驶；伪造、变造、买卖武装部队公文、证件、印章
妨害公务；寻衅滋事
非法转让、倒卖土地使用权；危险驾驶
容留他人吸毒；故意毁坏财物
非法拘禁；窝藏、包庇

# 筛选：案件名称包含“交通”

In [4]:
# 搜索“驾驶”是“危险驾驶罪”，一般都是醉驾/酒驾
# na=False 避免案件名称里有空值(NaN)时报错
# mask = df["案件名称"].astype(str).str.contains("交通", na=False)
mask = df["案由"].astype(str).str.contains("交通", na=False)
df_traffic = df[mask].copy()

# 查看筛选结果
print("筛选后条数：", len(df_traffic))
df_traffic.head()

筛选后条数： 41650

,原始链接,案号,案件名称,法院,所属地区,案件类型,案件类型编码,来源,审理程序,裁判日期,公开日期,当事人,案由,法律依据,全文
4,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）云0326执1104号,王朝磊、王明昌、刘兰兰与中国平安财产保险股份有限公司建水支公司机动车交通事故责任纠纷,会泽县人民法院,会泽县,执行案件,2,www.macrodatas.cn,执行实施,2020-01-01,2020-01-03,王朝磊；王明昌；刘兰兰；中国平安财产保险股份有限公司建水支公司,机动车交通事故责任纠纷,NaN,NaN
64,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）湘1321执59号,申请执行人黄辉与被执行人中国太平洋财产保险股份有限公司双峰支公司机动车交通事故责任纠纷执行实...,湖南省双峰县人民法院,湖南省双峰县,执行案件,2,www.macrodatas.cn,执行实施,2020-01-09,2020-01-10,黄辉；中国太平洋财产保险股份有限公司双峰支公司,机动车交通事故责任纠纷,NaN,湖南省双峰县人民法院执 结 通 知 书（2019）湘1321执59号申请执行人黄辉与被执行人...
76,https://wenshu.court.gov.cn/website/wenshu/181...,（2020）豫1303执恢1号,吴付军、孙延均机动车交通事故责任纠纷执行实施类执行通知书,河南省南阳市卧龙区人民法院,河南省南阳市,执行案件,2,www.macrodatas.cn,执行实施,2020-01-06,2020-01-10,吴付军、孙延均,机动车交通事故责任纠纷,NaN,河南省南阳市卧龙区人民法院结 案 通 知 书（2020）豫1303执恢1号吴付军、孙延均：本...
112,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）津0113民初8148号,"陈中娥与张飞,曹新胜,张海鹏等机动车交通事故责任纠纷",天津市北辰区人民法院,天津市,民事案件,1,www.macrodatas.cn,民事一审,2020-01-03,2020-01-15,陈中娥；曹新胜；中国人民财产保险股份有限公司北京市分公司,机动车交通事故责任纠纷,NaN,NaN
119,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）京0105民初83166号,吴某某、姜某机动车交通事故责任纠纷一审民事其他文书,北京市朝阳区人民法院,北京市,民事案件,1,www.macrodatas.cn,民事一审,2020-01-07,2020-01-09,吴某某；姜某,机动车交通事故责任纠纷,NaN,NaN

# 筛选：将全文内容为空的筛选出去

In [6]:
# 1) 把全文标准化：NaN -> ""，并去掉首尾空白
fulltext = df_traffic["全文"].fillna("").astype(str).str.strip()

# 2) 过滤条件：不为空、且不是字符串 "nan"/"NaN"
non_empty_mask = fulltext.ne("") & (~fulltext.str.lower().eq("nan"))

df_traffic_nonempty = df_traffic[non_empty_mask].copy()

print("去掉全文为空后条数：", len(df_traffic_nonempty))

df_traffic_nonempty

去掉全文为空后条数： 29579

,原始链接,案号,案件名称,法院,所属地区,案件类型,案件类型编码,来源,审理程序,裁判日期,公开日期,当事人,案由,法律依据,全文
64,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）湘1321执59号,申请执行人黄辉与被执行人中国太平洋财产保险股份有限公司双峰支公司机动车交通事故责任纠纷执行实...,湖南省双峰县人民法院,湖南省双峰县,执行案件,2,www.macrodatas.cn,执行实施,2020-01-09,2020-01-10,黄辉；中国太平洋财产保险股份有限公司双峰支公司,机动车交通事故责任纠纷,NaN,湖南省双峰县人民法院执 结 通 知 书（2019）湘1321执59号申请执行人黄辉与被执行人...
76,https://wenshu.court.gov.cn/website/wenshu/181...,（2020）豫1303执恢1号,吴付军、孙延均机动车交通事故责任纠纷执行实施类执行通知书,河南省南阳市卧龙区人民法院,河南省南阳市,执行案件,2,www.macrodatas.cn,执行实施,2020-01-06,2020-01-10,吴付军、孙延均,机动车交通事故责任纠纷,NaN,河南省南阳市卧龙区人民法院结 案 通 知 书（2020）豫1303执恢1号吴付军、孙延均：本...
178,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）鲁1703民初2415号,游志阳与李召华、巨野县海川运输有限公司机动车交通事故责任纠纷一审民事裁定书,山东省菏泽市定陶区人民法院,山东省菏泽市,民事案件,1,www.macrodatas.cn,民事一审,2020-01-07,2020-01-09,游志阳；李召华；巨野县海川运输有限公司；中国太平洋财产保险股份有限公司菏泽中心支公司,机动车交通事故责任纠纷,《中华人民共和国民事诉讼法》:第一百四十五条第一款,山东省菏泽市定陶区人民法院 民 事 裁 定 书 （2019）鲁1703民初2415号 原...
209,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）浙0226民初6585号,袁姣娣与叶新富、宁海县月盛城乡公共交通有限公司机动车交通事故责任纠纷一审民事判决书,宁海县人民法院,宁海县,民事案件,1,www.macrodatas.cn,民事一审,2020-01-02,2020-01-15,袁姣娣；叶新富；宁海县月盛城乡公共交通有限公司；中国太平洋财产保险股份有限公司宁海支公司,机动车交通事故责任纠纷,《中华人民共和国民法通则（2009修正）》:第一百一十九条；《中华人民共和国侵权责任法》:第...,浙江省宁海县人民法院 民 事 判 决 书 （2019）浙0226民初6585号 原告：袁姣...
384,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）苏1291民初2496号,2496周霞儿与沈春艳、王月珍等机动车交通事故责任纠纷一审民事裁定书,江苏省泰州医药高新技术产业开发区人民法院,江苏省,民事案件,1,www.macrodatas.cn,民事一审,2020-01-02,2020-01-13,周霞儿；沈春艳；王月珍；都邦财产保险股份有限公司泰州中心支公司,机动车交通事故责任纠纷,《中华人民共和国民事诉讼法》:第一百四十五条第一款；《中华人民共和国民事诉讼法》:第一百五十...,江苏省泰州医药高新技术产业开发区人民法院民 事 裁 定 书（2019）苏1291民初2496...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923368,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）苏0621执2689号,夏富珍与王世龙机动车交通事故责任纠纷执行裁定书,江苏省海安市人民法院,江苏省海安市,执行案件,2,www.macrodatas.cn,执行实施,2020-01-16,2021-09-03,夏富珍；王世龙,机动车交通事故责任纠纷,《中华人民共和国民事诉讼法》:第一百五十四条第一款第八项；《中华人民共和国民事诉讼法》:第二...,江苏省海安市人民法院执 行 裁 定 书（2019）苏0621执2689号申请人：夏富珍，女，...
923512,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）粤1322民初4186号,翟雪美、肖志军等机动车交通事故责任纠纷民事一审民事判决书,博罗县人民法院,博罗县,民事案件,1,www.macrodatas.cn,民事一审,2020-01-03,2021-09-16,翟雪美；肖志军；英德市路安运输有限公司；中国人民财产保险股份有限公司清远市分公司；中国太平洋...,机动车交通事故责任纠纷,《中华人民共和国侵权责任法》:第六条第一款；《中华人民共和国侵权责任法》:第六条第二款；《中...,广东省博罗县人民法院民 事 判 决 书（2019）粤1322民初4186号原告翟雪美，女，汉...
923676,https://wenshu.court.gov.cn/website/wenshu/181...,（2021）黔2701执167号,杨荣菊、蒙耀进机动车交通事故责任纠纷首次执行执行裁定书,都匀市人民法院,都匀市,执行案件,2,www.macrodatas.cn,执行实施,2020-01-19,2021-09-28,杨荣菊；蒙耀进,机动车交通事故责任纠纷,《中华人民共和国民事诉讼法》:第二百五十七条第六项,贵州省都匀市人民法院执 行 裁 定 书(2021)黔2701执167号申请执行人杨荣菊，女，...
923680,https://wenshu.court.gov.cn/website/wenshu/181...,（2021）粤0106民初517号,黄培全、蒋夏玉等机动车交通事故责任纠纷民事一审民事裁定书,广东省广州市天河区人民法院,广东省广州市,民事案件,1,www.macrodatas.cn,民事一审,2020-01-27,2021-09-07,黄培全；蒋夏玉；沈裕标；中国平安财产保险股份有限公司东莞分公司亨美营销服务部,机动车交通事故责任纠纷,《中华人民共和国民事诉讼法》:第一百一十八条第一款；《中华人民共和国民事诉讼法》:第一百一十...,广东省广州市天河区人民法院民 事 裁 定 书（2021）粤0106民初517号原告：黄培全，...
923763,https://wenshu.court.gov.cn/website/wenshu/181...,（2019）黑1202民初4905号,关国新、刘雨桐等机动车交通事故责任纠纷民事一审民事判决书,绥化市北林区人民法院,绥化市,民事案件,1,www.macrodatas.cn,民事一审,2020-01-06,2021-09-23,关国新；刘雨桐；太平财产保险有限公司绥化中心支公司,机动车交通事故责任纠纷,《中华人民共和国侵权责任法》:第十六条；《中华人民共和国侵权责任法》:第四十八条；《中华人民...,黑龙江省绥化市北林区人民法院 民 事 判 决 书 （2019）黑1202民初4905号 原...

# 筛选：只保留某几列

In [8]:
keep_cols = ["案号", "法院", "所属地区", "案件类型", "裁判日期", "当事人", "案由", "全文"]
df_traffic_clean = df_traffic_nonempty.loc[:, [c for c in keep_cols if c in df_traffic_nonempty.columns]].copy()

df_traffic_clean

,案号,法院,所属地区,案件类型,裁判日期,当事人,案由,全文
64,（2019）湘1321执59号,湖南省双峰县人民法院,湖南省双峰县,执行案件,2020-01-09,黄辉；中国太平洋财产保险股份有限公司双峰支公司,机动车交通事故责任纠纷,湖南省双峰县人民法院执 结 通 知 书（2019）湘1321执59号申请执行人黄辉与被执行人...
76,（2020）豫1303执恢1号,河南省南阳市卧龙区人民法院,河南省南阳市,执行案件,2020-01-06,吴付军、孙延均,机动车交通事故责任纠纷,河南省南阳市卧龙区人民法院结 案 通 知 书（2020）豫1303执恢1号吴付军、孙延均：本...
178,（2019）鲁1703民初2415号,山东省菏泽市定陶区人民法院,山东省菏泽市,民事案件,2020-01-07,游志阳；李召华；巨野县海川运输有限公司；中国太平洋财产保险股份有限公司菏泽中心支公司,机动车交通事故责任纠纷,山东省菏泽市定陶区人民法院 民 事 裁 定 书 （2019）鲁1703民初2415号 原...
209,（2019）浙0226民初6585号,宁海县人民法院,宁海县,民事案件,2020-01-02,袁姣娣；叶新富；宁海县月盛城乡公共交通有限公司；中国太平洋财产保险股份有限公司宁海支公司,机动车交通事故责任纠纷,浙江省宁海县人民法院 民 事 判 决 书 （2019）浙0226民初6585号 原告：袁姣...
384,（2019）苏1291民初2496号,江苏省泰州医药高新技术产业开发区人民法院,江苏省,民事案件,2020-01-02,周霞儿；沈春艳；王月珍；都邦财产保险股份有限公司泰州中心支公司,机动车交通事故责任纠纷,江苏省泰州医药高新技术产业开发区人民法院民 事 裁 定 书（2019）苏1291民初2496...
...,...,...,...,...,...,...,...,...
923368,（2019）苏0621执2689号,江苏省海安市人民法院,江苏省海安市,执行案件,2020-01-16,夏富珍；王世龙,机动车交通事故责任纠纷,江苏省海安市人民法院执 行 裁 定 书（2019）苏0621执2689号申请人：夏富珍，女，...
923512,（2019）粤1322民初4186号,博罗县人民法院,博罗县,民事案件,2020-01-03,翟雪美；肖志军；英德市路安运输有限公司；中国人民财产保险股份有限公司清远市分公司；中国太平洋...,机动车交通事故责任纠纷,广东省博罗县人民法院民 事 判 决 书（2019）粤1322民初4186号原告翟雪美，女，汉...
923676,（2021）黔2701执167号,都匀市人民法院,都匀市,执行案件,2020-01-19,杨荣菊；蒙耀进,机动车交通事故责任纠纷,贵州省都匀市人民法院执 行 裁 定 书(2021)黔2701执167号申请执行人杨荣菊，女，...
923680,（2021）粤0106民初517号,广东省广州市天河区人民法院,广东省广州市,民事案件,2020-01-27,黄培全；蒋夏玉；沈裕标；中国平安财产保险股份有限公司东莞分公司亨美营销服务部,机动车交通事故责任纠纷,广东省广州市天河区人民法院民 事 裁 定 书（2021）粤0106民初517号原告：黄培全，...
923763,（2019）黑1202民初4905号,绥化市北林区人民法院,绥化市,民事案件,2020-01-06,关国新；刘雨桐；太平财产保险有限公司绥化中心支公司,机动车交通事故责任纠纷,黑龙江省绥化市北林区人民法院 民 事 判 决 书 （2019）黑1202民初4905号 原...

In [10]:
df_traffic_clean.to_csv("../2020年裁判文书数据_马克数据网/2020_01.csv", index=False, encoding="utf-8-sig")