# 将shp中的中文翻译成英文

## 读取数据

In [17]:
import geopandas as gpd
import re

# pip install pypinyin
from pypinyin import lazy_pinyin

# 1) 读城市边界 GeoJSON
city_gdf = gpd.read_file("/Users/wl/Paper_First/202601交通数据集LLM/data/figure/china_geodata/中国_市.geojson")

In [19]:
city_gdf

    name         gb                                           geometry
0    梅州市  156441400  MULTIPOLYGON (((115.88406 24.92896, 115.89031 ...
1    鄂州市  156420700  MULTIPOLYGON (((114.83199 30.5678, 114.82968 3...
2    吕梁市  156141100  MULTIPOLYGON (((111.20539 38.72164, 111.20739 ...
3    舟山市  156330900  MULTIPOLYGON (((122.25205 29.69094, 122.23384 ...
4    朝阳市  156211300  MULTIPOLYGON (((119.6002 42.27468, 119.60812 4...
..   ...        ...                                                ...
383  陇南市  156621200  MULTIPOLYGON (((105.24292 34.52701, 105.2453 3...
384  保山市  156530500  MULTIPOLYGON (((98.7239 25.82049, 98.7109 25.8...
385  遂宁市  156510900  MULTIPOLYGON (((105.90684 30.48512, 105.91431 ...
386  合肥市  156340100  MULTIPOLYGON (((117.19746 32.52641, 117.20584 ...
387  铜川市  156610200  MULTIPOLYGON (((109.20601 35.56597, 109.21323 ...

[388 rows x 3 columns]

## 提取线数据，因为无法保存

In [30]:
# 只保留 Polygon / MultiPolygon
poly_gdf = city_gdf[city_gdf.geometry.geom_type.isin(["Polygon", "MultiPolygon"])].copy()

# 看看被剔除的是哪些（可选）
bad = city_gdf[~city_gdf.geometry.geom_type.isin(["Polygon", "MultiPolygon"])]
print("Non-polygon geometries:")
print(bad[["name"]].assign(geom_type=bad.geometry.geom_type))

Non-polygon geometries:
    name        geom_type
17   境界线  MultiLineString
23   境界线  MultiLineString
53   境界线  MultiLineString
76   境界线  MultiLineString
166  境界线  MultiLineString
182  境界线  MultiLineString
201  境界线  MultiLineString
214  境界线  MultiLineString
236  境界线  MultiLineString
239  境界线  MultiLineString
262  境界线  MultiLineString
289  境界线  MultiLineString
317  境界线  MultiLineString

In [33]:
# 2) 中文行政后缀清理（按需要可继续加）
SUFFIX_PATTERN = r"(市|地区|盟|自治州|自治县|县|区|旗|自治旗|林区|特区|保护区|省|自然保护区|特别行政区|地区)$"

def cn2eng_pinyin(name_cn: str) -> str:
    if name_cn is None:
        return None
    s = str(name_cn).strip()
    # 去掉末尾常见行政后缀
    s = re.sub(SUFFIX_PATTERN, "", s)
    # 转拼音（不带声调），并把每个音节首字母大写后拼接
    py = lazy_pinyin(s)
    eng = "".join([p.capitalize() for p in py])
    return eng

poly_gdf["name_eng"] = poly_gdf["name"].apply(cn2eng_pinyin)

In [35]:
poly_gdf

,name,gb,geometry,name_eng
0,梅州市,156441400,"MULTIPOLYGON (((115.88406 24.92896, 115.89031 ...",MeiZhou
1,鄂州市,156420700,"MULTIPOLYGON (((114.83199 30.5678, 114.82968 3...",EZhou
2,吕梁市,156141100,"MULTIPOLYGON (((111.20539 38.72164, 111.20739 ...",LvLiang
3,舟山市,156330900,"MULTIPOLYGON (((122.25205 29.69094, 122.23384 ...",ZhouShan
4,朝阳市,156211300,"MULTIPOLYGON (((119.6002 42.27468, 119.60812 4...",ZhaoYang
...,...,...,...,...
383,陇南市,156621200,"MULTIPOLYGON (((105.24292 34.52701, 105.2453 3...",LongNan
384,保山市,156530500,"MULTIPOLYGON (((98.7239 25.82049, 98.7109 25.8...",BaoShan
385,遂宁市,156510900,"MULTIPOLYGON (((105.90684 30.48512, 105.91431 ...",SuiNing
386,合肥市,156340100,"MULTIPOLYGON (((117.19746 32.52641, 117.20584 ...",HeFei
387,铜川市,156610200,"MULTIPOLYGON (((109.20601 35.56597, 109.21323 ...",TongChuan

In [39]:
# 3) 导出 Shapefile
out_path = "/Users/wl/Paper_First/202601交通数据集LLM/data/figure/china_geodata/中国_市_eng.shp"

# Shapefile对字段名长度有限制（通常<=10），name_eng刚好8没问题
# 注意：Shapefile对编码敏感，写入时指定UTF-8更稳（不同GDAL版本表现略有差异）
poly_gdf.to_file(out_path, driver="ESRI Shapefile", encoding="utf-8")

print("Done! Saved to:", out_path)
print(poly_gdf[["name", "name_eng"]])

Done! Saved to: /Users/wl/Paper_First/202601交通数据集LLM/data/figure/china_geodata/中国_市_eng.shp
    name   name_eng
0    梅州市    MeiZhou
1    鄂州市      EZhou
2    吕梁市    LvLiang
3    舟山市   ZhouShan
4    朝阳市   ZhaoYang
..   ...        ...
383  陇南市    LongNan
384  保山市    BaoShan
385  遂宁市    SuiNing
386  合肥市      HeFei
387  铜川市  TongChuan

[375 rows x 2 columns]